#!/bin/bash
. ./functions/printTitle.sh
. ./functions/prueba-palabra-audio.sh
. ./functions/prueba-palabra-espanol.sh
. ./functions/isRetrievableEnglishWord.sh
. ./functions/configuracion-colores.sh
. ./functions/configuracion-directorios.sh
. ./functions/imprimir-traduccion-ingresada.sh
. ./functions/reproduce-audio.sh
. ./functions/despliega-menu-de-decision.sh
. ./functions/despliega-opcion-agregar-palabra.sh
. ./functions/descargar-audio-de-google.sh
. ./functions/buscar-palabra-en-google.sh
. ./functions/existe-archivo-en-espanol.sh
. ./functions/existe-archivo-en-ingles.sh
. ./functions/agregar-palabra.sh
. ./functions/transfiere-traduccion-espanol.sh
. ./functions/crear-archivo-espanol.sh
. ./functions/transfiere-traduccion-ingles.sh
. ./functions/crear-archivo-ingles.sh
. ./functions/obtener-traduccion.sh
. ./functions/convierte-mp3-wav.sh
. ./functions/descargar-mp3-google.sh
. ./functions/cuenta-lineas-archivo-ingles.sh
. ./functions/cuenta-lineas-archivo-espanol.sh
. ./functions/desplegar-traduccion-espanol.sh
. ./functions/displayEnglishTranslation.sh
. ./functions/imprimir-campos-ingles.sh
. ./functions/obtener-campos-ingles.sh
. ./functions/imprimir-campos-espanol.sh
. ./functions/obtener-campos-espanol.sh
. ./functions/limpiar-archivo-espanol.sh
. ./functions/limpiar-archivo-ingles.sh
. ./functions/prueba-existencia.sh
