#!/bin/bash
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/imprimir-titulo.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/prueba-palabra-audio.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/prueba-palabra-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/prueba-palabra-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/configuracion-colores.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/configuracion-directorios.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/imprimir-traduccion-ingresada.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/reproduce-audio.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/despliega-menu-de-decision.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/despliega-opcion-agregar-palabra.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/descargar-audio-de-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/buscar-palabra-en-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/existe-archivo-en-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/existe-archivo-en-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/agregar-palabra.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/transfiere-traduccion-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/crear-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/transfiere-traduccion-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/crear-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/obtener-traduccion.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/convierte-mp3-wav.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/descargar-mp3-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/cuenta-lineas-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/cuenta-lineas-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/desplegar-traduccion-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/desplegar-traduccion-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/imprimir-campos-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/obtener-campos-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/imprimir-campos-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/obtener-campos-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/limpiar-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/limpiar-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DictEnEsScript/prueba-existencia.sh
