#!/bin/bash
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/imprimir-titulo.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/prueba-palabra-audio.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/prueba-palabra-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/prueba-palabra-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/configuracion-colores.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/configuracion-directorios.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/imprimir-traduccion-ingresada.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/reproduce-audio.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/despliega-menu-de-decision.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/despliega-opcion-agregar-palabra.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/descargar-audio-de-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/buscar-palabra-en-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/existe-archivo-en-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/existe-archivo-en-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/agregar-palabra.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/transfiere-traduccion-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/crear-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/transfiere-traduccion-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/crear-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/obtener-traduccion.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/convierte-mp3-wav.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/descargar-mp3-google.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/cuenta-lineas-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/cuenta-lineas-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/desplegar-traduccion-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/desplegar-traduccion-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/imprimir-campos-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/obtener-campos-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/imprimir-campos-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/obtener-campos-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/limpiar-archivo-espanol.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/limpiar-archivo-ingles.sh
. /Users/Carlossantiagocruz/Documents/BASH-PROGRAMMING/DICT-EN-ES/prueba-existencia.sh
